// Generated by scripts/generate-preset-graph.mjs from preset-graph.json.
// Do not edit this file directly.

export const ANIME4K_MODES = ["A","B","C","AA","BB","CA"] as const;
export type Anime4KMode = (typeof ANIME4K_MODES)[number];

export const QUALITY_TIERS = ["M","VL","UL"] as const;
export type QualityTier = (typeof QUALITY_TIERS)[number];

export type PresetStep = 'ClampHighlights' | 'Restore' | 'RestoreSoft' | 'Upscale' | 'DenoiseUpscale';

export const OFFICIAL_PRESET_GRAPHS = {
  "A": [
    "ClampHighlights",
    "Restore",
    "Upscale"
  ],
  "B": [
    "ClampHighlights",
    "RestoreSoft",
    "Upscale"
  ],
  "C": [
    "ClampHighlights",
    "DenoiseUpscale"
  ],
  "AA": [
    "ClampHighlights",
    "Restore",
    "Upscale",
    "Restore",
    "Upscale"
  ],
  "BB": [
    "ClampHighlights",
    "RestoreSoft",
    "Upscale",
    "RestoreSoft",
    "Upscale"
  ],
  "CA": [
    "ClampHighlights",
    "DenoiseUpscale",
    "Restore",
    "Upscale"
  ]
} as const satisfies Record<Anime4KMode, readonly PresetStep[]>;
